options:
    target:
        type: string
        default:
        description: 'ISCSI target IP'
    port:
        type: string
        default:
        description: 'ISCSI target port'
    discovery-and-login:
        type: boolean
        default: True
        description: |
            If set to True (default), the charm will configure the iscsid.conf and 
            multipathd.conf configuration files, and then run a iscsiadm discovery and login
            against the target. If set to False, the charm will simply configure the unit
            but not run the discovery and login against the target. 
    initiator-dictionary:
        type: string
        default: '{}'
        description: |
            Dictionary of hostnames (fqdn) and initiator names, surrounded by 
            single quotes. The charm compares the machine hostname to 
            the list, and provide the correct initiator associated to 
            it. If not defined, the initiator name will be provided 
            randomly. Format : 
            '{"hostname1": "iqn.yyyy-mm.naming-authority:uniquename1",
              "hostname2": "iqn.yyyy-mm.naming-authority:uniquename2}'
    multipath-conf-devices:
        type: string
        default:
        description: |
            In multipath.conf, add a device specific configuration. String should be of json dictionary format. 
            Example: 
                value : '{"vendor":"PURE","product": "FlashArray","fast_io_fail_tmo": "10", "path_grouping_policy":"group_by_prio"}'
                will produce this configuration:
                device {
                    vendor "PURE"
                    product "FlashArray"
                    fast_io_fail_tmo 10
                    path_grouping_policy "group_by_prio"
                }
    iscsi-node-session-auth-authmethod:
        type: string
        default:
        description: Authentication method (CHAP or None). Default is None.
    iscsi-node-session-auth-username:
        type: string
        default: ''
        description: CHAP username for initiator authentication by the target
    iscsi-node-session-auth-password:
        type: string
        default: ''
        description: CHAP password for initiator authentication by the target
    iscsi-node-session-auth-username-in:
        type: string
        default: ''
        description: CHAP username for target authentication by the initiator
    iscsi-node-session-auth-password-in:
        type: string
        default: ''
        description: CHAP password for target authentication by the initiator
    iscsi-node-startup:
        type: string
        default: automatic
        description: Startup setting for sessions. Either 'automatic' or 'manual'
    iscsi-node-session-iscsi-fastabort:
        type: string
        default: 'Yes'
        description: |
            Some targets like IET prefer after an initiator has sent a task
            management function like an ABORT TASK or LOGICAL UNIT RESET, that
            it does not respond to PDUs like R2Ts. To enable this behavior, set
            this config option to 'Yes'. To disable it, set it to 'No'.
    iscsi-node-session-scan:
        type: string
        default: auto
        description: |
            Automatic scans are performed on startup, on login, and on AEN/AER
            reception on devices supporting it. To prevent doing automatic scans
            that would add unwanted luns to the system, set to 'manual'. Default
            is 'auto'.
