options:
    storage-type:
        type: string
        default: None
        description: |
            Type of storage connection. Can either be "iscsi" or "fc" for fibre channel. The storage type cannot be changed after deployment.
    fc-lun-alias:
        type: string
        default: data1
        description: |
            LUN alias to give to the WWID for the mapping of the device. It is used in the path of the new mounted device, i.e /dev/mapper/<FC-LUN-ALIAS>.
    iscsi-target:
        type: string
        default:
        description: 'ISCSI target IP'
    iscsi-port:
        type: string
        default:
        description: 'ISCSI target port'
    iscsi-discovery-and-login:
        type: boolean
        default: True
        description: |
            If set to True (default) and storage-type is iscsi, the charm will configure
            the iscsid and multipath configuration files, and then run an iscsiadm
            discovery and login against the target. If set to False, the charm will simply
            configure the unit but not run the discovery and login against the target.
    initiator-dictionary:
        type: string
        default: '{}'
        description: |
            Dictionary of hostnames (FQDN) and initiator names, surrounded by
            single quotes. The charm compares the machine hostname to
            the list, and provide the correct initiator associated to
            it. If not defined, the initiator name will be provided
            randomly. Format :
            '{"hostname1": "iqn.yyyy-mm.naming-authority:uniquename1",
              "hostname2": "iqn.yyyy-mm.naming-authority:uniquename2}'
    enable-auto-restarts:
        type: boolean
        default: False
        description: |
            Allow the charm and packages to restart services automatically when
            required.
    multipath-defaults:
        type: string
        default: '{"user_friendly_names": "yes"}'
        description: |
            In multipath config, sets the defaults configuration. String should be of JSON dictionary format.
            Double quotes are essential to the correct format of this JSON string.
            Example:
                value : '{"user_friendly_names":"yes", "find_multipaths":"yes", "polling_interval":"10"}'
                Which will produce this configuration:
                defaults {
                    user_friendly_names yes
                    find_multipaths yes
                    polling_interval 10
                }
    multipath-devices:
        type: string
        default:
        description: |
            In multipath config, add a device specific configuration. String should be of JSON dictionary format.
            Double quotes are essential to the correct format of this JSON string.
            Example:
                value : '{"vendor":"PURE","product": "FlashArray","fast_io_fail_tmo": "10", "path_grouping_policy":"group_by_prio"}'
                Which will produce this configuration:
                device {
                    vendor "PURE"
                    product "FlashArray"
                    fast_io_fail_tmo 10
                    path_grouping_policy "group_by_prio"
                }
    multipath-blacklist:
        type: string
        default:
        description: |
            In multipath config, add a blacklist device section to exclude local disks from being handled by multipath-tools. It is possible
            to blacklist by vendor/product, by devnode or WWID. String should be of JSON dictionary format. Double quotes are essential to the correct format of this JSON string.
            Example:
                value: '{"vendor": "QEMU", "product": "*"}'
                Which will produce this configuration:
                blacklist {
                    device {
                        vendor "QEMU"
                        product "*"
                    }
                }
    iscsi-node-session-auth-authmethod:
        type: string
        default:
        description: Authentication method (CHAP or None). Default is None.
    iscsi-node-session-auth-username:
        type: string
        default: ''
        description: CHAP username for initiator authentication by the target
    iscsi-node-session-auth-password:
        type: string
        default: ''
        description: CHAP password for initiator authentication by the target
    iscsi-node-session-auth-username-in:
        type: string
        default: ''
        description: CHAP username for target authentication by the initiator
    iscsi-node-session-auth-password-in:
        type: string
        default: ''
        description: CHAP password for target authentication by the initiator
    iscsi-node-startup:
        type: string
        default: automatic
        description: Startup setting for sessions. Either 'automatic' or 'manual'
    iscsi-node-session-iscsi-fastabort:
        type: string
        default: 'Yes'
        description: |
            Some targets like IET prefer after an initiator has sent a task
            management function like an ABORT TASK or LOGICAL UNIT RESET, that
            it does not respond to PDUs like R2Ts. To enable this behavior, set
            this config option to 'Yes'. To disable it, set it to 'No'.
    iscsi-node-session-scan:
        type: string
        default: auto
        description: |
            Automatic scans are performed on startup, on login, and on AEN/AER
            reception on devices supporting it. To prevent doing automatic scans
            that would add unwanted luns to the system, set to 'manual'. Default
            is 'auto'.
    nagios_context:
        default: "juju"
        type: string
        description: |
            A string that will be prepended to instance name to set the host name
            in nagios. So for instance the hostname would be something like:
                juju-myservice-0
            If you're running multiple environments with the same services in them
            this allows you to differentiate between them.
    nagios_multipath_paths_per_volume:
        default: 4
        type: int
        description: |
            Number of expected paths per volume. Any number other than this will
            raise a CRITICAL nagios alert.
