defaults { 
  user_friendly_names yes 
  find_multipaths yes 
  polling_interval 10 
} 
devices { 
  device { 
    vendor "PURE" 
    product "FlashArray" 
    path_selector "queue-length 0" 
    path_grouping_policy "group_by_prio" 
    rr_min_io 1 
    path_checker tur 
    fast_io_fail_tmo 1 
    dev_loss_tmo infinity 
    no_path_retry 5 
    failback immediate 
    prio alua 
    hardware_handler "1 alua" 
    max_sectors_kb 4096 
  } 
}
multipaths { 
  multipath { 
    wwid "3624a9370da36a876e11946730001415e" 
    alias data1 
  } 
}
