# This is a template `pr.yaml` file for ops charms
# This file is managed by bootstack-charms-spec and should not be modified
# within individual charm repos. https://launchpad.net/bootstack-charms-spec

name: PR workflow running lint checkers, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
    with:
      python-version: ${{ matrix.python-version }}

  func:
    uses: canonical/bootstack-actions/.github/workflows/func.yaml@v3
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        command: ["TEST_JUJU3=1 make functional"]  # TEST_JUJU3 needed due https://github.com/openstack-charmers/zaza/blob/b22c2eed4c322f1dfc14ffb2d31e0dd18c911a40/setup.py#L47 to support Juju3+
        juju-channel: ["3.4/stable"]
    with:
      command: ${{ matrix.command }}
      juju-channel: ${{ matrix.juju-channel }}
      nested-containers: false
      provider: "lxd"
      python-version: "3.10"
      timeout-minutes: 120
      runs-on: "['self-hosted', 'runner-storage-connector']"
      action-operator: false
      external-controller: true
      juju-controller: soleng-ci-ctrl-34
      zaza-yaml: "LS0tCm1vZGVsX3NldHRpbmdzOgogIGltYWdlLXN0cmVhbTogcmVsZWFzZWQKcmVnaW9uOiBwcm9kc3RhY2s2CmNsb3VkOiBidWlsZGVyLWNsb3VkCmNyZWRlbnRpYWw6IGJ1aWxkZXItY2xvdWQtY3JlZAoK"
    secrets:
      juju-controllers-yaml: ${{ secrets.JUJU_CONTROLLERS_YAML }}
      juju-accounts-yaml: ${{ secrets.JUJU_ACCOUNTS_YAML }}
      openstack-auth-env: ${{ secrets.OPENSTACK_AUTH_ENV }}
